### ISSUE TITLE
Sort Direction

### ISSUE THREAD

**Issue by lalbok** [shirsig/SortBags-vanilla#5]
Hi, I don't know if I'm doing it correctly but when I'm trying to change the direction of sorting /run SetSortBagsRightToLeft(0) but it does not apply.

**Comment by shirsig** [comment]
`/run SetSortBagsRightToLeft(true)` to activate it, `/run SetSortBagsRightToLeft(false)` to deactivate it.

**Comment by lalbok** [comment]
I have tried /run SetSortBagsRightToLeft(false) but it still sorts items from right to left

**Comment by shirsig** [comment]
Unfortunately I don't have a vanilla client or account anymore to test it, but I don't understand how it could suddenly be broken since the vanilla client is always the same...
Maybe try reloading as well:
`/run SetSortBagsRightToLeft(false)`
`/run ReloadUI()`
`/run SortBags()`

**Comment by lalbok** [comment]
Did not work either. Well It is okay not a biggie. Thank you for your effort!
